#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1449712222.947
__CHEETAH_genTimestamp__ = 'Wed Dec 09 19:50:22 2015'
__CHEETAH_src__ = 'controlDict.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Dec 09 19:41:56 2015'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class controlDict(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(controlDict, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\\\    /   O peration     | Version:  2.4.0                                 |
|   \\\\  /    A nd           | Web:      www.OpenFOAM.org                      |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    location    "system";
    object      controlDict;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

application     ''')
        _v = VFFSL(SL,"node.application",True) # u'$node.application' on line 18, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'$node.application')) # from line 18, col 17.
        write(u''';

startFrom       ''')
        _v = VFFSL(SL,"node.startFrom",True) # u'$node.startFrom' on line 20, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'$node.startFrom')) # from line 20, col 17.
        write(u''';

startTime       ''')
        _v = VFFSL(SL,"node.startTime",True) # u'$node.startTime' on line 22, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'$node.startTime')) # from line 22, col 17.
        write(u''';

stopAt          ''')
        _v = VFFSL(SL,"node.stopAt",True) # u'$node.stopAt' on line 24, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'$node.stopAt')) # from line 24, col 17.
        write(u''';

endTime         ''')
        _v = VFFSL(SL,"node.endTime",True) # u'$node.endTime' on line 26, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'$node.endTime')) # from line 26, col 17.
        write(u''';

deltaT          ''')
        _v = VFFSL(SL,"node.deltaT",True) # u'$node.deltaT' on line 28, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'$node.deltaT')) # from line 28, col 17.
        write(u''';

writeControl    ''')
        _v = VFFSL(SL,"node.writeControl",True) # u'$node.writeControl' on line 30, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'$node.writeControl')) # from line 30, col 17.
        write(u''';

writeInterval   ''')
        _v = VFFSL(SL,"node.writeInterval",True) # u'$node.writeInterval' on line 32, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'$node.writeInterval')) # from line 32, col 17.
        write(u''';

purgeWrite      ''')
        _v = VFFSL(SL,"node.purgeWrite",True) # u'$node.purgeWrite' on line 34, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'$node.purgeWrite')) # from line 34, col 17.
        write(u''';

writeFormat     ''')
        _v = VFFSL(SL,"node.writeFormat",True) # u'$node.writeFormat' on line 36, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'$node.writeFormat')) # from line 36, col 17.
        write(u''';

writePrecision  ''')
        _v = VFFSL(SL,"node.writePrecision",True) # u'$node.writePrecision' on line 38, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'$node.writePrecision')) # from line 38, col 17.
        write(u''';

writeCompression ''')
        _v = VFFSL(SL,"node.writeCompression",True) # u'$node.writeCompression' on line 40, col 18
        if _v is not None: write(_filter(_v, rawExpr=u'$node.writeCompression')) # from line 40, col 18.
        write(u''';

timeFormat      ''')
        _v = VFFSL(SL,"node.timeFormat",True) # u'$node.timeFormat' on line 42, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'$node.timeFormat')) # from line 42, col 17.
        write(u''';

timePrecision   ''')
        _v = VFFSL(SL,"node.timePrecision",True) # u'$node.timePrecision' on line 44, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'$node.timePrecision')) # from line 44, col 17.
        write(u''';

graphFormat     ''')
        _v = VFFSL(SL,"node.graphFormat",True) # u'$node.graphFormat' on line 46, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'$node.graphFormat')) # from line 46, col 17.
        write(u''';

runTimeModifiable ''')
        _v = VFFSL(SL,"node.runTimeModifiable",True) # u'$node.runTimeModifiable' on line 48, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$node.runTimeModifiable')) # from line 48, col 19.
        write(u''';


// ************************************************************************* //
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_controlDict= 'respond'

## END CLASS DEFINITION

if not hasattr(controlDict, '_initCheetahAttributes'):
    templateAPIClass = getattr(controlDict, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(controlDict)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=controlDict()).run()


